name: Python LSA Search Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        make install  # Uses your Makefile to install dependencies

    - name: Run the web application
      run: |
        make run &  # Start your Flask app using Makefile
        sleep 10  # Give time for the server to start
